source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'JIRA Commander' do
  pod 'QorumLogs'
  pod 'Alamofire', '~> 3.0'
  pod '1PasswordExtension', :git => 'https://github.com/AgileBits/onepassword-app-extension.git'
end

